apiVersion: v1
kind: Service
metadata:
  name: project-one-service
spec:
  selector:
    app: project-one  
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 7010 
  type: LoadBalancer