name: Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: project-1-400619
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker gcr.io

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/project-1-400619/wed_proj_test:${{ github.run_number }} .
          docker tag gcr.io/project-1-400619/wed_proj_test:${{ github.run_number }} gcr.io/project-1-400619/wed_proj_test:latest
          docker push gcr.io/project-1-400619/wed_proj_test:${{ github.run_number }}
          docker push gcr.io/project-1-400619/wed_proj_test:latest
          
        
  deploy:
  
      runs-on: ubuntu-latest
      needs: build
        
      steps: 

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: project-1-400619
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true
      
      - name: Set Kubectl Context
        run: gcloud container clusters get-credentials 	google-test-1 --zone us-central1 --project project-1-400619 

      - name: Deploy to GKE
        run: |
          docker pull gcr.io/project-1-400619/wed_proj_test:${{ github.run_number }}
          kubectl rollout  restart  -f deployment.yaml
          kubectl apply -f deployment.yaml
          
      - name: Create LoadBalancer Service
        run: kubectl apply -f service.yaml
